# Generated by Django 5.1.1 on 2026-06-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sync_interval_seconds', models.IntegerField(default=3600, help_text='Desired sync interval in seconds')),
                ('total_items_ingested', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
