# Generated by Django 5.1.1 on 2026-06-16 05:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_accounts_user_org_role_idx_accounts_us_organiz_f36d76_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatActor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='List of known aliases')),
                ('description', models.TextField(blank=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('target_sectors', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateField(blank=True, null=True)),
                ('last_seen', models.DateField(blank=True, null=True)),
                ('threat_score', models.IntegerField(default=50, help_text='0-100 score')),
            ],
            options={
                'ordering': ['-threat_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cve_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('is_kev', models.BooleanField(db_index=True, default=False, help_text='Known Exploited Vulnerability')),
                ('kev_added_date', models.DateField(blank=True, null=True)),
                ('kev_due_date', models.DateField(blank=True, null=True)),
                ('kev_action', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ['-cvss_score', '-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(default='CyTrack Auto-Intel', max_length=255)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.organization')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorOfCompromise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(db_index=True, max_length=2048)),
                ('type', models.CharField(choices=[('ipv4', 'IPv4 Address'), ('ipv6', 'IPv6 Address'), ('domain', 'Domain Name'), ('url', 'URL'), ('md5', 'MD5 Hash'), ('sha1', 'SHA-1 Hash'), ('sha256', 'SHA-256 Hash'), ('email', 'Email Address'), ('mutex', 'Mutex')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('confidence', models.IntegerField(default=50, help_text='0-100 confidence score')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('sources', models.JSONField(default=list, help_text='List of sources that reported this IOC (e.g. OTX, AbuseIPDB)')),
                ('threat_actors', models.ManyToManyField(blank=True, related_name='iocs', to='intelligence.threatactor')),
                ('vulnerabilities', models.ManyToManyField(blank=True, related_name='iocs', to='intelligence.vulnerability')),
            ],
            options={
                'verbose_name': 'IOC',
                'verbose_name_plural': 'IOCs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'value'], name='intelligenc_type_3bc4a9_idx')],
                'unique_together': {('type', 'value')},
            },
        ),
    ]
