# Generated by Django 5.1.1 on 2026-06-16 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '__first__'),
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorofcompromise',
            name='sources',
        ),
        migrations.AddField(
            model_name='indicatorofcompromise',
            name='source_nodes',
            field=models.ManyToManyField(blank=True, related_name='iocs', to='ingestion.source'),
        ),
        migrations.AddField(
            model_name='indicatorofcompromise',
            name='sources_json',
            field=models.JSONField(blank=True, default=list, help_text='Legacy list of sources'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='base_score_v3',
            field=models.FloatField(blank=True, help_text='CVSS v3 Base Score', null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='severity_v3',
            field=models.CharField(blank=True, help_text='CVSS v3 Severity (e.g. HIGH, CRITICAL)', max_length=20),
        ),
        migrations.CreateModel(
            name='ThreatPulse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('external_id', models.CharField(db_index=True, help_text='External ID (e.g., OTX pulse ID)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('iocs', models.ManyToManyField(blank=True, related_name='pulses', to='intelligence.indicatorofcompromise')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulses', to='ingestion.source')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
