# Generated by Django 5.1.1 on 2026-06-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_remove_indicatorofcompromise_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='affected_products',
            field=models.JSONField(blank=True, default=list, help_text='CPE strings for affected products'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='cvss_v2_score',
            field=models.FloatField(blank=True, help_text='CVSS v2 Base Score', null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='references',
            field=models.JSONField(blank=True, default=list, help_text='NVD reference URLs'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='vector_string',
            field=models.CharField(blank=True, help_text='CVSS vector string', max_length=100),
        ),
    ]
